---
# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation

version: "3.5"

services:
    server:
        # Build a container from a Dockerfile.
        build:
            # Context for Docker to build the image (relative to this file).
            context: ./

            # Filename of the Dockerfile to use, relative to the context.
            dockerfile: Dockerfile

            args:
                - USER_ID=${INSTALL_USER_ID}

        # If you specify "image" as well as "build", Compose names the built
        # image. Syntax is "IMAGE[:TAG]".
        image: test
        container_name: test_server

        # Restart policy
        restart: "always"
