---
# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation


version: "3.5"



services:

    test:
        build:
            context: ./

            dockerfile: Dockerfile

        image: crute

        restart: "always"
