---
# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation


version: "3.5"


services:

    test:
        build:
            context: ./

            # Filename of the Dockerfile to use, relative to the context.
            dockerfile: Dockerfile

        image: test

        # Restart policy
        restart: "always"

        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - test_network


# =============================================================================
# Networks
# =============================================================================

networks:
    test_network:
        driver: bridge
