---
# yamllint disable rule:line-length
name: Docker Compose v2.14.0
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - .github/workflows/installer-2.14.0.yml
            - github_action_scripts/installer_setup.sh
            - github_action_scripts/set_crate_docker_environment
            - 'docker/**'
            - 'installer/**'
            - setup.py
jobs:
    installer:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Run installer
              run: |
                set -eux -o pipefail
                DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
                mkdir -p ${DOCKER_CONFIG}/cli-plugins
                docker version
                docker compose version
                # Something in 2.14.1 broke the installer.
                echo "Installing older Docker Compose..."
                curl -SL https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-x86_64 -o ${DOCKER_CONFIG}/cli-plugins/docker-compose
                chmod ugo+x ${DOCKER_CONFIG}/cli-plugins/docker-compose
                docker compose version
                source ${GITHUB_WORKSPACE}/github_action_scripts/set_crate_docker_environment
                ${GITHUB_WORKSPACE}/github_action_scripts/installer_setup.sh
                cd ${GITHUB_WORKSPACE}/installer
                ./installer.sh -d
